name: Build for ARM

on:
  push:
    branches:
      - main  # 触发条件可以根据你的需求进行调整

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu Runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17  # 选择 Go 版本

    - name: Build for ARM
      run: |
        export GOARCH=arm
        export GOARM=7  # 根据你的 ARM 架构版本进行调整
        go build -o myapp-arm

    - name: Upload ARM binary
      uses: actions/upload-artifact@v2
      with:
        name: myapp-arm
        path: ./myapp-arm
